# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# C:\ci\containers\00000go6b48\tmp\build\80754af9\combined_recipe, last modified Mon Jun 28 11:34:00 2021
# ------------------------------------------------

package:
  name: pip
  version: 21.1.3
source:
  sha256: b5b1eb91b36894bd01b8e5a56a422c2f3838573da0b0a1c63a096bb454e3b23f
  url: https://pypi.io/packages/source/p/pip/pip-21.1.3.tar.gz
build:
  disable_pip: true
  entry_points:
    - pip = pip._internal.cli.main:main
    - pip3 = pip._internal.cli.main:main
  number: '0'
  string: py39haa95532_0
requirements:
  host:
    - ca-certificates 2021.5.25 haa95532_1
    - certifi 2021.5.30 py39haa95532_0
    - openssl 1.1.1k h2bbff1b_0
    - python 3.9.5 h6244533_3
    - setuptools 52.0.0 py39haa95532_0
    - sqlite 3.36.0 h2bbff1b_0
    - tzdata 2021a h52ac0ba_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wincertstore 0.2 py39h2bbff1b_0
  run:
    - python >=3.9,<3.10.0a0
    - setuptools
    - wheel
test:
  commands:
    - pip -h
    - pip list
  imports:
    - pip
about:
  dev_url: https://github.com/pypa/pip
  doc_url: https://pip.pypa.io/en/stable/
  home: https://pip.pypa.io/en/stable/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: PyPA recommended tool for installing Python packages
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
