# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# C:\ci\containers\00003gmdu0o\tmp\build\80754af9\rsync-recipes\ruamel_yaml-0.15.100-python_3.9-on-winbuilder, last modified Wed Mar 17 16:08:04 2021
# ------------------------------------------------

package:
  name: ruamel_yaml
  version: 0.15.100
source:
  sha256: 8e42f3067a59e819935a2926e247170ed93c8f0b2ab64526f888e026854db2e4
  url: https://pypi.io/packages/source/r/ruamel.yaml/ruamel.yaml-0.15.100.tar.gz
build:
  no_link: .*\.(pyd|dll)
  number: '0'
  string: py39h2bbff1b_0
requirements:
  build:
    - m2-base 1.0.0 3
    - m2-bash 4.3.042 5
    - m2-bash-completion 2.3 2
    - m2-catgets 1.1 3
    - m2-coreutils 8.25 102
    - m2-dash 0.5.8 2
    - m2-diffutils 3.3 4
    - m2-file 5.25 2
    - m2-filesystem 2016.04 4
    - m2-findutils 4.6.0 2
    - m2-gawk 4.1.3 2
    - m2-gcc-libs 5.3.0 4
    - m2-gettext 0.19.7 4
    - m2-gmp 6.1.0 3
    - m2-grep 2.22 4
    - m2-gzip 1.7 2
    - m2-inetutils 1.9.2 2
    - m2-info 6.0 2
    - m2-less 481 2
    - m2-libasprintf 0.19.7 4
    - m2-libbz2 1.0.6 3
    - m2-libcatgets 1.1 3
    - m2-libcrypt 1.3 2
    - m2-libgettextpo 0.19.7 4
    - m2-libiconv 1.14 3
    - m2-libintl 0.19.7 4
    - m2-liblzma 5.2.2 2
    - m2-libpcre 8.38 2
    - m2-libreadline 6.3.008 8
    - m2-libutil-linux 2.26.2 2
    - m2-libxml2 2.9.2 3
    - m2-make 4.1 5
    - m2-mintty 1!2.2.3 2
    - m2-mpfr 3.1.4 2
    - m2-msys2-launcher-git 0.3.28.860c495 2
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-ncurses 6.0.20160220 2
    - m2-sed 4.2.2 3
    - m2-tar 1.28 4
    - m2-tftp-hpa 5.2 2
    - m2-time 1.7 2
    - m2-ttyrec 1.0.8 2
    - m2-tzcode 2015.e 2
    - m2-unzip 6.0 3
    - m2-util-linux 2.26.2 2
    - m2-which 2.21 3
    - m2-zip 3.0 2
    - m2-zlib 1.2.8 4
    - msys2-conda-epoch 20160418 1
    - posix 1.0.0 2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.7.1 h21ff451_0
  host:
    - ca-certificates 2021.1.19 haa95532_1
    - certifi 2020.12.5 py39haa95532_0
    - cython 0.29.22 py39hd77b12b_0
    - openssl 1.1.1j h2bbff1b_0
    - pip 21.0.1 py39haa95532_0
    - python 3.9.2 h6244533_0
    - setuptools 52.0.0 py39haa95532_0
    - sqlite 3.35.1 h2bbff1b_0
    - tzdata 2020f h52ac0ba_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.36.2 pyhd3eb1b0_0
    - wincertstore 0.2 py39h2bbff1b_0
    - yaml 0.2.5 he774522_0
  run:
    - python >=3.9,<3.10.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
    - yaml >=0.2.5,<0.3.0a0
test:
  commands:
    - pip check
  imports:
    - ruamel_yaml
    - ruamel_yaml.ext._ruamel_yaml
  requires:
    - pip
about:
  home: https://sourceforge.net/p/ruamel-yaml/code/ci/default/tree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A patched copy of ruamel.yaml.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - isuruf
    - jakirkham
    - mbargull
