# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# C:\ci\containers\00000e0bsvn\tmp\build\80754af9\combined_recipe, last modified Tue Jun  1 10:47:17 2021
# ------------------------------------------------

package:
  name: certifi
  version: 2021.5.30
source:
  - folder: certifi
    sha256: 2bbf76fd432960138b3ef6dda3dde0544f27cbf8546c458e60baf371917ba9ee
    url: https://pypi.io/packages/source/c/certifi/certifi-2021.5.30.tar.gz
  - folder: pip_wheel
    sha256: 0f35d63b7245205f4060efe1982f5ea2196aa6e5b26c07669adcf800e2542026
    url: https://pypi.io/packages/py2.py3/p/pip/pip-20.2.3-py2.py3-none-any.whl
  - folder: setuptools_wheel
    sha256: 4dd5bb0a0a0cff77b46ca5dd3a84857ee48c83e8223886b556613c724994073f
    url: https://pypi.io/packages/py3/s/setuptools/setuptools-49.6.0-py3-none-any.whl
build:
  number: '0'
  string: py39haa95532_0
requirements:
  build: []
  host:
    - ca-certificates 2021.5.25 haa95532_1
    - openssl 1.1.1k h2bbff1b_0
    - python 3.9.5 h6244533_3
    - sqlite 3.35.4 h2bbff1b_0
    - tzdata 2020f h52ac0ba_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - python >=3.9,<3.10.0a0
test:
  imports:
    - certifi
about:
  description: 'Certifi is a curated collection of Root Certificates for validating
    the

    trustworthiness of SSL certificates while verifying the identity of TLS

    hosts.

    '
  dev_url: https://github.com/certifi/python-certifi
  doc_source_url: https://github.com/certifi/certifi.io/blob/master/README.rst
  doc_url: https://pypi.python.org/pypi/certifi
  home: https://github.com/certifi/python-certifi
  license: MPL-2.0
  license_file: certifi/LICENSE
  summary: Python package for providing Mozilla's CA Bundle.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - mingwandroid
    - ocefpaf
    - pelson
    - sigmavirus24
