# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# C:\ci\containers\0000160buv4\tmp\build\80754af9\rsync-recipes\menuinst-1.4.16-python_3.9-on-winbuilder, last modified Tue Dec  1 07:43:01 2020
# ------------------------------------------------

package:
    name: menuinst
    version: 1.4.16
source:
    git_rev: 1.4.16
    git_url: https://github.com/ContinuumIO/menuinst.git
build:
    entry_points:
        - menuinst = menuinst.main:main
    skip_compile_pyc:
        - cwp.py
    string: py39h2bbff1b_0
requirements:
    host:
        - ca-certificates 2020.10.14 0
        - certifi 2020.11.8 py39haa95532_0
        - openssl 1.1.1h he774522_0
        - python 3.9.0 h6244533_2
        - setuptools 50.3.2 py39haa95532_2
        - sqlite 3.33.0 h2a8f88b_0
        - tzdata 2020d h14c3975_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
        - wincertstore 0.2 py39h2bbff1b_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - python >=3.9,<3.10.0a0
        - pywin32
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    commands:
        - menuinst -h
        - menuinst --version
    imports:
        - menuinst
        - menuinst.winshortcut
about:
    description: 'This application is used by Conda to create shortcuts on a wide
        variety of

        systems.

        '
    dev_url: https://github.com/ContinuumIO/menuinst
    doc_source_url: https://github.com/ContinuumIO/menuinst
    doc_url: https://pypi.python.org/pypi/menuinst/
    home: https://github.com/ContinuumIO/menuinst
    license: BSD
    summary: cross platform menu item installation
extra:
    copy_test_source_files: true
    final: true
