# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00001aq4i5u\tmp\build\80754af9\rsync-recipes\powershell_shortcut-0.0.1-on-winbuilder, last modified Thu Jan 23 18:52:03 2020
# ------------------------------------------------

package:
    name: powershell_shortcut
    version: 0.0.1
build:
    number: '3'
    string: '3'
requirements:
    run:
        - python
    run_constrained:
        - anaconda-navigator >=1.9.8
app:
    entry: start powershell.exe -ExecutionPolicy ByPass -NoExit -Command  "& '{CONDA_ROOT_PREFIX}\\shell\\condabin\\conda-hook.ps1'
        ; conda activate '{CONDA_PREFIX}'"
    summary: Anaconda Powershell Prompt
    type: desk
about:
    license: BSD
    summary: Powershell shortcut creator for Windows (using menuinst)
extra:
    copy_test_source_files: true
    final: true
