ignore_build_only_deps:
- python
- numpy
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  libboost:
    max_pin: x.x.x
extend_keys:
- ignore_build_only_deps
- ignore_version
- pin_run_as_build
- extend_keys
tk:
- '8.6'
proj4:
- 5.2.0
bzip2:
- '1.0'
libprotobuf:
- 3.11.2
serf:
- 1.3.9
noarch_python:
- python
g2clib:
- '1.6'
cran_mirror:
- https://mran.microsoft.com/snapshot/2018-01-01
m2w64_fortran_compiler:
- m2w64-toolchain
giflib:
- '5'
hdf5:
- 1.10.6
macos_machine:
- x86_64-apple-darwin13.4.0
cairo:
- '1.14'
libnetcdf:
- '4.6'
pixman:
- '0.30'
jpeg:
- '9'
numpy:
- '1.16'
python_impl:
- cpython
freetype:
- '2.10'
libdap4:
- '3.19'
gmp:
- '6.1'
VERBOSE_AT:
- V=1
gst_plugins_base:
- '1.14'
libxslt:
- '1.1'
rust_compiler:
- rust-gnu
- rust
libgd:
- 2.2.5
gstreamer:
- '1.14'
boost_cpp:
- '1.73'
blas_impl:
- mkl
proj:
- 6.2.1
mkl:
- '2021'
lua:
- '5'
fontconfig:
- '2.13'
hdf4:
- '4.2'
gnu:
- 2.12.2
mpfr:
- '4'
apr:
- 1.6.3
libgsasl:
- '1.8'
libwebp:
- 1.0.0
cudatoolkit:
- '9.0'
target_platform:
- win-64
libffi:
- 3.2.1
MACOSX_DEPLOYMENT_TARGET:
- '10.9'
VERBOSE_CM:
- VERBOSE=1
icu:
- '58'
perl:
- '5.26'
lzo:
- '2'
cyrus_sasl:
- 2.1.26
openblas:
- 0.3.3
hdfeos5:
- '5.1'
readline:
- '8.0'
sqlite:
- '3'
m2w64_cxx_compiler:
- m2w64-toolchain
hdfeos2:
- '2.20'
libxml2:
- '2.9'
channel_targets:
- defaults
libgdal:
- '3.0'
libkml:
- '1.3'
r_implementation:
- r-base
- mro-base
qtwebkit:
- 'true'
cpu_optimization_target:
- nocona
r_base:
- '3.5'
openssl:
- 1.1.1
llvm_variant:
- llvm
dbus:
- '1'
boost:
- '1.73'
xz:
- '5'
cross_compiler_target_platform:
- win-32
- win-64
m2w64_c_compiler:
- m2w64-toolchain
rust_compiler_version:
- 1.46.0
openjpeg:
- '2.3'
fortran_compiler:
- intel-fortran
expat:
- '2.2'
libtiff:
- '4.1'
clang_variant:
- clang
r_version:
- 3.5.0
macos_min_version:
- '10.9'
python_implementation:
- cpython
harfbuzz:
- '2.4'
libpng:
- '1.6'
zlib:
- '1.2'
glib:
- '2'
geos:
- 3.8.0
cxx_compiler:
- vs2017
python:
- '3.9'
fortran_compiler_version:
- 2019.0.0
c_compiler:
- vs2017
vc:
- '14'
zip_keys:
- - vc
  - c_compiler
  - cxx_compiler
  - fortran_compiler_version
  - python
  - geos
