# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# C:\ci\containers\000004tfvkb\tmp\build\80754af9\rsync-recipes\brotlipy-0.7.0-python_3.9-on-winbuilder, last modified Mon Nov 16 14:22:49 2020
# ------------------------------------------------

package:
    name: brotlipy
    version: 0.7.0
source:
    fn: brotlipy-0.7.0.tar.gz
    sha256: 36def0b859beaf21910157b4c33eb3b06d8ce459c942102f16988cca6ea164df
    url: https://pypi.io/packages/source/b/brotlipy/brotlipy-0.7.0.tar.gz
build:
    number: '1003'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py39h2bbff1b_1003
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.10.14 0
        - certifi 2020.6.20 pyhd3eb1b0_3
        - cffi 1.14.3 py39hcd4344a_2
        - openssl 1.1.1h he774522_0
        - pycparser 2.20 py_2
        - python 3.9.0 h6244533_2
        - setuptools 50.3.1 py39haa95532_1
        - sqlite 3.33.0 h2a8f88b_0
        - tzdata 2020d h14c3975_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wincertstore 0.2 py39h2bbff1b_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - cffi >=1.0.0
        - python >=3.9,<3.10.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    imports:
        - brotli
about:
    dev_url: https://github.com/python-hyper/brotlipy
    home: https://github.com/python-hyper/brotlipy
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Python bindings to the Brotli compression library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - astaric
        - isuruf
        - primozgodec
