# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/pull-recipes-pycparser/recipe, last modified Fri Jul 10 13:41:12 2020
# ------------------------------------------------

package:
    name: pycparser
    version: '2.20'
source:
    fn: pycparser-2.20.tar.gz
    sha256: 2d475327684562c3a96cc71adf7dc8c4f0565175cf86b6d7a404ff4c771f15f0
    url: https://pypi.io/packages/source/p/pycparser/pycparser-2.20.tar.gz
build:
    noarch: python
    number: '2'
    script: /tmp/build/80754af9/pycparser_1594388511720/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . -vvv && cp -r utils ${SP_DIR}/pycparser
    string: py_2
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py37_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h7b6447c_0
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.1.1 py37_1
        - python 3.7.7 hcff3b4d_5
        - readline 8.0 h7b6447c_0
        - setuptools 47.3.1 py37_0
        - sqlite 3.32.3 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.34.2 py37_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    imports:
        - pycparser
        - pycparser.ply
about:
    description: 'pycparser is a complete parser of the C language, written in pure
        Python using the PLY parsing library.

        It parses C code into an AST and can serve as a front-end for C compilers
        or analysis tools.

        '
    dev_url: https://github.com/eliben/pycparser
    home: https://github.com/eliben/pycparser
    license: BSD-3-Clause
    license_file: LICENSE
    summary: Complete C99 parser in pure Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - scopatz
        - synapticarbors
