# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# C:\ci\containers\0000124pkl9\tmp\build\80754af9\rsync-recipes\win_inet_pton-1.1.0-python_3.9-on-winbuilder, last modified Mon Aug 17 15:42:55 2020
# ------------------------------------------------

package:
    name: win_inet_pton
    version: 1.1.0
source:
    sha256: dd03d942c0d3e2b1cf8bab511844546dfa5f74cb61b241699fa379ad707dea4f
    url: https://pypi.io/packages/source/w/win_inet_pton/win_inet_pton-1.1.0.tar.gz
build:
    number: '0'
    script: C:\ci\win_inet_pton_1605306162074\_h_env\python.exe -m pip install . --no-deps
        --ignore-installed --no-cache-dir -vvv
    string: py39haa95532_0
requirements:
    host:
        - ca-certificates 2020.10.14 0
        - certifi 2020.6.20 pyhd3eb1b0_3
        - openssl 1.1.1h he774522_0
        - pip 20.2.4 py39haa95532_0
        - python 3.9.0 h8aef87e_1
        - setuptools 50.3.1 py39haa95532_1
        - sqlite 3.33.0 h2a8f88b_0
        - tzdata 2020d h14c3975_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.35.1 pyhd3eb1b0_0
        - wincertstore 0.2 py39h2bbff1b_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - python >=3.9,<3.10.0a0
test:
    imports:
        - win_inet_pton
about:
    dev_url: https://github.com/hickeroar/win_inet_pton
    home: https://github.com/hickeroar/win_inet_pton
    license: PUBLIC-DOMAIN
    license_file: LICENSE
    summary: Native inet_pton and inet_ntop implementation for Python on Windows (with
        ctypes).
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - pmlandwehr
