# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# C:\ci\containers\00001621thh\tmp\build\80754af9\combined_recipe, last modified Fri Dec 11 11:13:21 2020
# ------------------------------------------------

package:
    name: chardet
    version: 4.0.0
source:
    sha256: 0d6f53a15db4120f2b08c94f11e7d93d2c911ee118b6b30a04ec3ee8310179fa
    url: https://pypi.io/packages/source/c/chardet/chardet-4.0.0.tar.gz
build:
    entry_points:
        - chardetect = chardet.cli.chardetect:main
    number: '1003'
    script: C:\ci\chardet_1607706937985\_h_env\python.exe -m pip install . --no-deps
        --ignore-installed --no-cache-dir -vvv
    string: py39haa95532_1003
requirements:
    host:
        - atomicwrites 1.4.0 py_0
        - attrs 20.3.0 pyhd3eb1b0_0
        - ca-certificates 2020.12.8 haa95532_0
        - certifi 2020.12.5 py39haa95532_0
        - colorama 0.4.4 py_0
        - importlib-metadata 2.0.0 py_1
        - importlib_metadata 2.0.0 1
        - iniconfig 1.1.1 py_0
        - more-itertools 8.6.0 pyhd3eb1b0_0
        - openssl 1.1.1i h2bbff1b_0
        - packaging 20.7 pyhd3eb1b0_0
        - pip 20.3.1 py39haa95532_0
        - pluggy 0.12.0 py_0
        - py 1.9.0 py_0
        - pyparsing 2.4.7 py_0
        - pytest 6.1.2 py39haa95532_0
        - pytest-runner 5.2 py_0
        - python 3.9.1 h6244533_2
        - setuptools 51.0.0 py39haa95532_2
        - six 1.15.0 py39haa95532_0
        - sqlite 3.33.0 h2a8f88b_0
        - toml 0.10.1 py_0
        - tzdata 2020d h14c3975_0
        - vc 14.2 h21ff451_1
        - vs2015_runtime 14.27.29016 h5e58377_2
        - wheel 0.36.1 pyhd3eb1b0_0
        - wincertstore 0.2 py39h2bbff1b_0
        - zipp 3.4.0 pyhd3eb1b0_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - python >=3.9,<3.10.0a0
test:
    commands:
        - chardetect --help
    imports:
        - chardet
about:
    description: 'chardet is a character encoding auto-detector in Python.

        '
    dev_url: https://github.com/chardet/chardet
    doc_source_url: https://github.com/chardet/chardet/blob/master/docs/index.rst
    doc_url: http://chardet.readthedocs.org/
    home: https://github.com/chardet/chardet
    license: LGPL2
    license_family: GPL
    license_file: LICENSE
    summary: Universal character encoding detector
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dan-blanchard
        - jschueller
        - nehaljwani
        - sigmavirus24
